### ISSUE TITLE
Grizly documentation on readthedocs

### ISSUE THREAD

**Issue by malinaa96** [kfk/grizly#182]
Let's gather all the stuff that we want to have in readthedocs in one place ([link to grizly docs](https://grizly-docs.readthedocs.io/en/master/index.html)). 

## [How to install](https://grizly-docs.readthedocs.io/en/master/content/how_to_install.html)

- [ ] Installing Anaconda
- [ ] [Add anaconda paths to environment variables](https://grizly-docs.readthedocs.io/en/master/content/how_to_install.html#add-anaconda-paths-to-environment-variables)
- [ ] [Add https proxy to environment variables](https://grizly-docs.readthedocs.io/en/master/content/how_to_install.html#add-https-proxy-to-environment-variables)
- [ ] Installing grizly

## [Tutorial - QFrame](https://grizly-docs.readthedocs.io/en/master/content/tutorial_qframe.html)

- [ ] [Working with the QFrame](https://grizly-docs.readthedocs.io/en/master/content/tutorial_qframe.html#working-with-the-qframe)
    - [ ] [Getting the sql](https://grizly-docs.readthedocs.io/en/master/content/tutorial_qframe.html#getting-the-sql)
    - [ ] [Doing some basic SQL stuff](https://grizly-docs.readthedocs.io/en/master/content/tutorial_qframe.html#doing-some-basic-sql-stuff)
    - [ ] [Forking](https://grizly-docs.readthedocs.io/en/master/content/tutorial_qframe.html#forking)
- [ ] [Joining data](https://grizly-docs.readthedocs.io/en/master/content/tutorial_qframe.html#joining-data)
- [ ] [Using the store.json](https://grizly-docs.readthedocs.io/en/master/content/tutorial_qframe.html#using-the-store-json)
- [ ] [In database workflow](https://grizly-docs.readthedocs.io/en/master/content/tutorial_qframe.html#in-database-workflow)

TODO: 
- [ ] add more stuff from README file

## [Tutorial - the Store](https://grizly-docs.readthedocs.io/en/master/content/tutorial_store.html)

- [ ] [Adding an SQL query to the json](https://grizly-docs.readthedocs.io/en/master/content/tutorial_store.html#adding-an-sql-query-to-the-json)
- [ ] [Use case, adding a conf key](https://grizly-docs.readthedocs.io/en/master/content/tutorial_store.html#use-case-adding-a-conf-key)
- [ ] [Remember get_columns()](https://grizly-docs.readthedocs.io/en/master/content/tutorial_store.html#remember-get-columns)
- [ ] [Key concepts of the store](https://grizly-docs.readthedocs.io/en/master/content/tutorial_store.html#key-concepts-of-the-store)

## Grizly functions

TODO: Put here the functions that we have in utils, each function should be a new subsection??

### Class Config

Feel free to share your ideas how this should look like.

**Comment by acivitillo** [comment]
Could we merge the tutorial and new tutorial and eliminate store?

**Comment by malinaa96** [comment]
Yes I will do it today. I just have some problems with importing grizly in jupyter because of this `__init__.py` file. Could you tell me what folder structure do you have? You have it like `%USERPROFILE%/grizly/grizly/..` or do you have grizly under another name?

**Comment by malinaa96** [comment]
I almost finished it, I'm missing join yet, I will finish it next week.

**Comment by malinaa96** [comment]
I merged both tutorials in 0.3 https://grizly-docs.readthedocs.io/en/0.3/content/api/tutorial_qframe_new.html
I this tutorial doesn't run automatically because I get errors with the paths. It works on my computer but when I check the docs online I'm getting errors. For now I live it like this but at this point I'm the only one who can run all the tests without errors.

**Comment by acivitillo** [comment]
@malinaa96 it seems to work for me if I go to the link but I see you still have the tutorial store there

**Comment by malinaa96** [comment]
You want to get rid of it completely?

**Comment by acivitillo** [comment]
I think we should as right now we don't use it and save data to .json directly from the tool Class

**Comment by malinaa96** [comment]
Ok, I removed it
